[package]
name = "mojang_api"
version = "0.1.0"
authors = ["caelunshun <caelunshun@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.18"
log = "0.4.6"
serde = "1.0.92"
serde_derive = "1.0.92"
serde_json = "1.0.39"

[dev-dependencies]
mockito = "0.17.1"