[package]
name = "mojang-api"
version = "0.2.0"
authors = ["caelunshun <caelunshun@gmail.com>"]
edition = "2018"
description = "A simple library for interfacing with the Mojang API. Includes full support for async/await syntax."
repository = "https://github.com/caelunshun/mojang-api-rs"
readme = "README.md"
categories = ["api-bindings"]
keywords = ["minecraft"]
license = "MIT/Apache-2.0"

[dependencies]
sha1 = "0.6"
num-bigint = "0.2"
futures-preview = { version = "0.3.0-alpha.17", features = ["compat"] }
reqwest = "0.9"
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "0.7", features = ["v4", "serde"] }

[dev-dependencies]
mockito = "0.20"
serde_json = "1.0"
tokio = { git = "https://github.com/tokio-rs/tokio" }